#!/bin/sh
echo "POST-COMMIT HOOK GOT CALLED"
`sudo cp -R /var/lib/jenkins/jobs/itrust2/workspace/iTrust2-v2/ /var/lib/jenkins/jobs/fuzzer/workspace/`
`curl -X POST http://${JENKINS_USER}:${JENKINS_PASSWORD}@localhost:9090/job/fuzzer/build -H $CRUMB`
